<?php

namespace ContainerU7XNdCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WCX6y_IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WCX6y.I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WCX6y.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeEntreprise' => ['privates', '.errored..service_locator.WCX6y.I.App\\Entity\\TypeEntreprise', NULL, 'Cannot autowire service ".service_locator.WCX6y.I": it references class "App\\Entity\\TypeEntreprise" but no such service exists.'],
        ], [
            'typeEntreprise' => 'App\\Entity\\TypeEntreprise',
        ]);
    }
}
