<?php

namespace ContainerU7XNdCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1Gc1j5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f1Gc1j5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f1Gc1j5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
        ], [
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
        ]);
    }
}
