<?php

namespace ContainerU7XNdCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEntrepriseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WCX6y.I.App\Entity\TypeEntreprise' shared service.
     *
     * @return \App\Entity\TypeEntreprise
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WCX6y.I": it references class "App\\Entity\\TypeEntreprise" but no such service exists.');
    }
}
