<?php

namespace ContainerU7XNdCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeEntrepriseTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TypeEntrepriseType' shared autowired service.
     *
     * @return \App\Form\TypeEntrepriseType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TypeEntrepriseType.php';

        return $container->privates['App\\Form\\TypeEntrepriseType'] = new \App\Form\TypeEntrepriseType();
    }
}
