<?php

namespace ContainerBE3sXtR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommerce2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vxfKQbX.App\Entity\Commerce' shared service.
     *
     * @return \App\Entity\Commerce
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vxfKQbX": it references class "App\\Entity\\Commerce" but no such service exists.');
    }
}
