<?php

namespace ContainerBE3sXtR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7u_0083.App\Entity\Specialite' shared service.
     *
     * @return \App\Entity\Specialite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7u_0083": it references class "App\\Entity\\Specialite" but no such service exists.');
    }
}
