<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7XNdCb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7XNdCb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU7XNdCb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU7XNdCb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU7XNdCb\App_KernelDevDebugContainer([
    'container.build_hash' => 'U7XNdCb',
    'container.build_id' => '6314c281',
    'container.build_time' => 1618061928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7XNdCb');
