<?php

namespace ContainerT9E02k5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQKGFXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fQKGF_X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fQKGF_X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commande' => ['privates', '.errored..service_locator.fQKGF_X.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.fQKGF_X": it references class "App\\Entity\\Commande" but no such service exists.'],
        ], [
            'commande' => 'App\\Entity\\Commande',
        ]);
    }
}
