<?php

namespace ContainerT9E02k5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DrUERLYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.drUERLY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.drUERLY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commerce' => ['privates', '.errored..service_locator.drUERLY.App\\Entity\\Commerce', NULL, 'Cannot autowire service ".service_locator.drUERLY": it references class "App\\Entity\\Commerce" but no such service exists.'],
            'produitRepo' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'commerce' => 'App\\Entity\\Commerce',
            'produitRepo' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
