<?php

namespace ContainerT9E02k5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VxfKQbXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vxfKQbX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vxfKQbX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commerce' => ['privates', '.errored..service_locator.vxfKQbX.App\\Entity\\Commerce', NULL, 'Cannot autowire service ".service_locator.vxfKQbX": it references class "App\\Entity\\Commerce" but no such service exists.'],
        ], [
            'commerce' => 'App\\Entity\\Commerce',
        ]);
    }
}
