<?php

namespace ContainerT9E02k5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommerceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CommerceType' shared autowired service.
     *
     * @return \App\Form\CommerceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CommerceType.php';

        return $container->privates['App\\Form\\CommerceType'] = new \App\Form\CommerceType();
    }
}
